"""
    Deutscher Wetterdienst: API

    Aktuelle Wetterdaten von allen Deutschen Wetterstationen  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.dwd.model.crowd_meldung_meldungen_inner import (
    CROWDMeldungMeldungenInner,
)

from deutschland import dwd


class TestCROWDMeldungMeldungenInner(unittest.TestCase):
    """CROWDMeldungMeldungenInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCROWDMeldungMeldungenInner(self):
        """Test CROWDMeldungMeldungenInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CROWDMeldungMeldungenInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
