"""
    Deutscher Wetterdienst: API

    Aktuelle Wetterdaten von allen Deutschen Wetterstationen  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.dwd.model.station_overview10865_days_inner import (
    StationOverview10865DaysInner,
)

from deutschland import dwd


class TestStationOverview10865DaysInner(unittest.TestCase):
    """StationOverview10865DaysInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStationOverview10865DaysInner(self):
        """Test StationOverview10865DaysInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StationOverview10865DaysInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
