"""
    Deutscher Wetterdienst: API

    Aktuelle Wetterdaten von allen Deutschen Wetterstationen  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.dwd.model.warning_nowcast_warnings_inner_regions_inner import (
    WarningNowcastWarningsInnerRegionsInner,
)

from deutschland import dwd

globals()[
    "WarningNowcastWarningsInnerRegionsInner"
] = WarningNowcastWarningsInnerRegionsInner
from deutschland.dwd.model.gemeinde_warnings_warnings_inner import (
    GemeindeWarningsWarningsInner,
)


class TestGemeindeWarningsWarningsInner(unittest.TestCase):
    """GemeindeWarningsWarningsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGemeindeWarningsWarningsInner(self):
        """Test GemeindeWarningsWarningsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GemeindeWarningsWarningsInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
