"""
    Deutscher Wetterdienst: API

    Aktuelle Wetterdaten von allen Deutschen Wetterstationen  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.dwd.model.crowd_meldung_highest_severities_inner import (
    CROWDMeldungHighestSeveritiesInner,
)

from deutschland import dwd


class TestCROWDMeldungHighestSeveritiesInner(unittest.TestCase):
    """CROWDMeldungHighestSeveritiesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCROWDMeldungHighestSeveritiesInner(self):
        """Test CROWDMeldungHighestSeveritiesInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CROWDMeldungHighestSeveritiesInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
