"""
    Deutscher Wetterdienst: API

    Aktuelle Wetterdaten von allen Deutschen Wetterstationen  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.dwd.model.gemeinde_warnings_binnen_see209901000_inner import (
    GemeindeWarningsBinnenSee209901000Inner,
)

from deutschland import dwd


class TestGemeindeWarningsBinnenSee209901000Inner(unittest.TestCase):
    """GemeindeWarningsBinnenSee209901000Inner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGemeindeWarningsBinnenSee209901000Inner(self):
        """Test GemeindeWarningsBinnenSee209901000Inner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GemeindeWarningsBinnenSee209901000Inner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
