"""
    Deutscher Wetterdienst: API

    Aktuelle Wetterdaten von allen Deutschen Wetterstationen  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.dwd.model.crowd_meldung_meldungen import CROWDMeldungMeldungen

from deutschland import dwd


class TestCROWDMeldungMeldungen(unittest.TestCase):
    """CROWDMeldungMeldungen unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCROWDMeldungMeldungen(self):
        """Test CROWDMeldungMeldungen"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CROWDMeldungMeldungen()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
