"""
    Deutscher Wetterdienst: API

    Aktuelle Wetterdaten von allen Deutschen Wetterstationen  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.dwd.model.crowd_meldung_highest_severities import (
    CROWDMeldungHighestSeverities,
)
from deutschland.dwd.model.crowd_meldung_meldungen import CROWDMeldungMeldungen

from deutschland import dwd

globals()["CROWDMeldungHighestSeverities"] = CROWDMeldungHighestSeverities
globals()["CROWDMeldungMeldungen"] = CROWDMeldungMeldungen
from deutschland.dwd.model.crowd_meldung import CROWDMeldung


class TestCROWDMeldung(unittest.TestCase):
    """CROWDMeldung unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCROWDMeldung(self):
        """Test CROWDMeldung"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CROWDMeldung()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
