"""
    Deutscher Wetterdienst: API

    Aktuelle Wetterdaten von allen Deutschen Wetterstationen  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.dwd.model.warning_nowcast_regions import WarningNowcastRegions

from deutschland import dwd

globals()["WarningNowcastRegions"] = WarningNowcastRegions
from deutschland.dwd.model.gemeinde_warnings_warnings import GemeindeWarningsWarnings


class TestGemeindeWarningsWarnings(unittest.TestCase):
    """GemeindeWarningsWarnings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGemeindeWarningsWarnings(self):
        """Test GemeindeWarningsWarnings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GemeindeWarningsWarnings()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
