"""
    Deutscher Wetterdienst: API

    Aktuelle Wetterdaten von allen Deutschen Wetterstationen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.dwd.model.warning_nowcast_regions import WarningNowcastRegions

from deutschland import dwd


class TestWarningNowcastRegions(unittest.TestCase):
    """WarningNowcastRegions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWarningNowcastRegions(self):
        """Test WarningNowcastRegions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WarningNowcastRegions()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
